#ONE DIMENSIONAL ARRAY PRACTICE

In [ ]:
#create an array and traverse
import numpy as np
arr = np.array([1,2,3,4,5])
for i in arr:
    print(i)

1
2
3
4
5


In [ ]:
#access individual element through indexes
arr=np.array([1,2,3,4,5])
print(arr[4])


5


In [ ]:
#append any value to the array using append() method
arr=np.array([1,2,3,4,5])
arr=np.append(arr,8)
arr

array([1, 2, 3, 4, 5, 8])

In [ ]:
#insert any value in an array using insert() method
arr=np.insert(arr,0,0)
arr


array([0, 1, 2, 3, 4, 5, 8])

In [ ]:
#extent python array using python extend function()
print(arr)

[0 1 2 3 4 5 8]


In [ ]:
arr1=np.array([9,8,7])

In [ ]:
arr2=np.concatenate((arr,arr1))
arr2

array([0, 1, 2, 3, 4, 5, 8, 9, 8, 7])

In [ ]:
#add items from list into array using fromlist() method
import array
my_array = array.array('i',[1,2,3,4,5])
list1=[1,2,3,4]
my_array.fromlist(list1)
my_array

array('i', [1, 2, 3, 4, 5, 1, 2, 3, 4])

In [ ]:
#remove any array element using remove() method
my_array.remove(2)
my_array


array('i', [1, 3, 4, 5, 1, 2, 3, 4])

In [ ]:
#remove last array element using pop() method
my_array.pop()
my_array

array('i', [1, 3, 4, 5, 1, 2, 3])

In [ ]:
#fetch any element through its index using index() method
my_array.index(3)
my_array

array('i', [1, 3, 4, 5, 1, 2, 3])

In [ ]:
#reverse pyhton array using reverse() method
my_array.reverse()
print(my_array)

array('i', [3, 2, 1, 5, 4, 3, 1])


In [ ]:
#get the array buffer infromation through buffer_info() method
print(my_array.buffer_info())

(136074535954080, 7)


In [ ]:
#check the number of occurrences of an element using count() method
print(my_array)
print(my_array.count(1))

array('i', [3, 2, 1, 5, 4, 3, 1])
2


In [ ]:
#convert array to string using tobytes() method
arr5=my_array.tobytes()
print(arr5)

b'\x03\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00\x04\x00\x00\x00\x03\x00\x00\x00\x01\x00\x00\x00'


In [ ]:
#convert array to a python list with same elements using tolist()
list2=my_array.tolist()
list2

[3, 2, 1, 5, 4, 3, 1]

In [ ]:
#slice elements from an array
print(my_array[1:4])
print(my_array)

array('i', [2, 1, 5])
array('i', [3, 2, 1, 5, 4, 3, 1])


#TWO DIMENSINAL

In [ ]:
#day-1 11,15,10,6
#day-2 10,14,11,5
#day-3 12,17,12,8
#day-4 15,18,14,9
tdarray=np.array([[11,15,10,6],[10,14,11,5],[12,17,12,8],[15,18,14,9]])
tdarray

array([[11, 15, 10,  6],
       [10, 14, 11,  5],
       [12, 17, 12,  8],
       [15, 18, 14,  9]])

In [ ]:
#insert
new2darray=np.insert(tdarray,0,[[1,2,3,4]],axis=0)
new2darray

array([[ 1,  2,  3,  4],
       [11, 15, 10,  6],
       [10, 14, 11,  5],
       [12, 17, 12,  8],
       [15, 18, 14,  9]])

In [ ]:
#access an element
def accesselement(array,rowindex,columnindex):
  if rowindex>=len(array) or columnindex>=len(array[0]):
    print('incorrect index')
  else:
    print(array[rowindex][columnindex])

accesselement(tdarray,7,1)


incorrect index


In [ ]:
#traversal of array
def traversearray(array):
  for i in range(len(array)):
    for j in range(len(array[0])):
      print(array[i][j])
traversearray(tdarray)

11
15
10
6
10
14
11
5
12
17
12
8
15
18
14
9


In [ ]:
#search an array
print(tdarray)
def searcharray(array,element):
  for i in range(len(array)):
    for j in range(len(array[0])):
      if array[i][j]==element:
        print(i,j)

searcharray(tdarray,17)


[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
2 1


In [ ]:
#delete an array
new2darray = np.delete(tdarray,0,axis=1)
new2darray

array([[15, 10,  6],
       [14, 11,  5],
       [17, 12,  8],
       [18, 14,  9]])